countries = ['Afghanistan',
             'Aland Islands',
             'Albania',
             'Algeria',
             'American Samoa',
             'Andorra',
             'Angola',
             'Anguilla',
             'Antarctica',
             'Antigua and Barbuda',
             'Argentina',
             'Armenia',
             'Aruba',
             'Australia',
             'Austria',
             'Azerbaijan',
             'Bahamas',
             'Bahrain',
             'Bangladesh',
             'Barbados',
             'Belgium',
             'Belize',
             'Benin',
             'Bermuda',
             'Bhutan',
             'Bolivia',
             'Bonaire, Saint Eustatius and Saba',
             'Bosnia and Herzegovina',
             'Botswana',
             'Bouvet Island',
             'Brazil',
             'British Indian Ocean Territory',
             'Brunei Darussalam',
             'Bulgaria',
             'Burkina Faso',
             'Burundi',
             'Cambodia',
             'Cameroon',
             'Canada',
             'Canary Islands',
             'Cape Verde',
             'Cayman Islands',
             'Central African Republic',
             'Ceuta and Melilla',
             'Chad',
             'Chile',
             'China',
             'Christmas Island',
             'Cocos (Keeling) Islands',
             'Colombia',
             'Comoros',
             'Congo, Democratic Republic of',
             'Congo, Republic of',
             'Cook Islands',
             'Costa Rica',
             'Croatia/Hrvatska',
             'Curacao',
             'Cyprus',
             'Czech Republic',
             'Denmark',
             'Djibouti',
             'Dominica',
             'Dominican Republic',
             'East Timor',
             'Ecuador',
             'Egypt',
             'El Salvador',
             'Equatorial Guinea',
             'Eritrea',
             'Estonia',
             'Ethiopia',
             'Falkland Islands',
             'Faroe Islands',
             'Fiji',
             'Finland',
             'France',
             'French Guiana',
             'French Polynesia',
             'French Southern Territories',
             'Gabon',
             'Gambia',
             'Georgia',
             'Germany',
             'Ghana',
             'Gibraltar',
             'Greece',
             'Greenland',
             'Grenada',
             'Guadeloupe',
             'Guam',
             'Guatemala',
             'Guernsey',
             'Guinea',
             'Guinea-Bissau',
             'Guyana',
             'Haiti',
             'Heard and McDonald Islands',
             'Holy See (City Vatican State)',
             'Honduras',
             'Hong Kong',
             'Hungary',
             'Iceland',
             'India',
             'Indonesia',
             'Iraq',
             'Ireland',
             'Isle of Man',
             'Israel',
             'Italy',
             'Jamaica',
             'Japan',
             'Jersey',
             'Jordan',
             'Kazakhstan',
             'Kenya',
             'Kiribati',
             'Korea, Republic of',
             'Kosovo',
             'Kuwait',
             'Kyrgyzstan',
             'Latvia',
             'Lesotho',
             'Liberia',
             'Liechtenstein',
             'Lithuania',
             'Luxembourg',
             'Macau',
             'Macedonia',
             'Madagascar',
             'Malawi',
             'Malaysia',
             'Maldives',
             'Mali',
             'Malta',
             'Marshall Islands',
             'Martinique',
             'Mauritania',
             'Mauritius',
             'Mayotte',
             'Mexico',
             'Micronesia, Federal State of',
             'Moldova, Republic of',
             'Monaco',
             'Mongolia',
             'Montenegro',
             'Montserrat',
             'Morocco',
             'Mozambique',
             'Myanmar (Burma)',
             'Namibia',
             'Nauru',
             'Nepal',
             'Netherlands',
             'Netherlands Antilles',
             'New Caledonia',
             'New Zealand',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'Niue',
             'Norfolk Island',
             'Northern Mariana Islands',
             'Norway',
             'Oman',
             'Pakistan',
             'Palau',
             'Panama',
             'Papua New Guinea',
             'Paraguay',
             'Peru',
             'Philippines',
             'Pitcairn Island',
             'Poland',
             'Portugal',
             'Puerto Rico',
             'Qatar',
             'Reunion Island',
             'Romania',
             'Russian Federation',
             'Rwanda',
             'Saint Barthelemy',
             'Saint Helena',
             'Saint Kitts and Nevis',
             'Saint Lucia',
             'Saint Martin',
             'Saint Vincent and the Grenadines',
             'Samoa',
             'San Marino',
             'Sao Tome and Principe',
             'Saudi Arabia',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Sierra Leone',
             'Singapore',
             'Sint Maarten',
             'Slovak Republic',
             'Slovenia',
             'Solomon Islands',
             'South Africa',
             'South Georgia',
             'South Sudan',
             'Spain',
             'Sri Lanka',
             'St. Pierre and Miquelon',
             'State of Palestine',
             'Suriname',
             'Svalbard and Jan Mayen Islands',
             'Swaziland',
             'Sweden',
             'Switzerland',
             'Taiwan',
             'Tajikistan',
             'Tanzania',
             'Thailand',
             'Togo',
             'Tokelau',
             'Tonga',
             'Trinidad and Tobago',
             'Tunisia',
             'Turkey',
             'Turkmenistan',
             'Turks and Caicos Islands',
             'Tuvalu',
             'US Minor Outlying Islands',
             'Uganda',
             'Ukraine',
             'United Arab Emirates',
             'United Kingdom',
             'United States',
             'Uruguay',
             'Uzbekistan',
             'Vanuatu',
             'Venezuela',
             'Vietnam',
             'Virgin Islands (British)',
             'Virgin Islands (USA)',
             'Wallis and Futuna',
             'Western Sahara',
             'Yemen',
             'Zambia']
